# https://files.minecraftforge.net/net/minecraftforge/forge/
modLoader = "javafml"
loaderVersion = "[46,)"
license = "GPL-3"
issueTrackerURL="https://github.com/p0t4t0sandwich/LeafDecayNt/issues"

[[mods]]
modId = "leafdecaynt"
version = "${file.jarVersion}"
displayName = "LeafDecayNt"
updateJSONURL="https://raw.githubusercontent.com/p0t4t0sandwich/LeafDecayNt/main/forgeUpdates.json"
displayURL="https://github.com/p0t4t0sandwich/LeafDecayNt"
logoFile="LeafDecayNt.png"
credits="p0t4t0sandwich"
authors="p0t4t0sandwich"
displayTest="IGNORE_SERVER_VERSION"
description = '''
Plugin that prevents leaves from decaying
'''

# Forge Dependency
[[dependencies.leafdecaynt]]
modId = "forge"
mandatory = true
versionRange = "[46,)"
ordering = "NONE"
side = "BOTH"

# Minecraft Dependency
[[dependencies.leafdecaynt]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,1.21)"
ordering = "NONE"
side = "BOTH"
